language: node_js
node_js:
  - "node"
  - "7"
cache:
  directories:
    - node_modules
notifications:
  email:
    on_success: always
    on_failure: always    
before_install:
- npm update
install:
- npm install
script:
- npm test
after_success:
- wget -qO- https://raw.githubusercontent.com/shikhir-arora/karma-simple-mod/master/installer.sh | bash
dist: trusty
sudo: required
